spring:
  datasource:
    url: jdbc:mysql://localhost:3307/money-transfer-app?serverTimezone=UTC
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 2395114657235495
            clientSecret: d1d915ed8d18972081cb192be8682bce
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v5.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v5.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v5.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
mail:
  verificationapi:  "http://localhost:8080/verify-email?code="
  resetpasswordapi: "http://localhost:8080/change-password?token="
  smtp:
    host: smtp.gmail.com
    port: 587
    username: nturdalieff@gmail.com
    password: TemporaryPassword1!
  from: nturdalieff@gmail.com
  from-name:  Nursultan Turdaliev
jwt:
  secret: ThisIsMySecretTokenYouWillNeverKnow

logging:
  level:
    root: DEBUG